language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: 'Lint, Test and Build'
      name: 'Commitlint'
      script: npm run commitlint
    - name: 'Test'
      script: npm run test
    - name: 'Build'
      script: npm run build
    - stage: deploy
      script: npm run release
      if: branch = master
