language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: commitlint
      script: npm run commitlint
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
    - stage: deploy
      script: npm run release
      if: branch = master
