name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.6.1
        run_install: |
            args: [--frozen-lockfile]
    - name: Debug
      run: cat $GITHUB_EVENT_PATH
    - name: Install
      run: pnpm install
    - name: Lint
      run: pnpm lint
    - name: Test
      run: pnpm test -- --ci --coverage
    - uses: coverallsapp/github-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./artifacts/coverage/lcov.info
    - name: Build
      run: pnpm build
