name: Build

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Install
      run: |
        yarn install
    - name: Lint
      run: |
        yarn lint
    - name: Test
      env:
        CI: true
      run: |
        yarn test -- --ci --coverage
    - name: Report
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        yarn coveralls
    - name: Build
      run: |
        yarn build
    - name: Deploy
      if: matrix.node-version == '12.x' && github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn release
