name: Rebase

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: boilerplate-ejection
        token: ${{ secrets.GH_TOKEN }}
    - run: git rebase origin/main
    - run: git push --force --set-upstream origin boilerplate-ejection
