name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0/15 * * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Renovate
        uses: renovatebot/github-action@v25.36.0
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.GH_TOKEN }}
