name: Renovate

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: renovatebot/github-action@v31.38.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_TOKEN }}
